os: linux
dist: xenial
language: c
script:
  - ./binaries/hugo # This commands builds your website on travis
before_deploy: cd public && git status
deploy:
  provider: script
  script:
  - git add .
  - git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"
  - git remote add origin-pages https://${GTOKEN}@github.com/${GUSER}/${GREPONAME}.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin-pages master
  skip_cleanup: true
  local_dir: public
  keep_history: true
  target_branch: master
  on:
    branch: master
