os: linux
dist: xenial
language: c
script:
  - ./binaries/hugo # This command builds blog with hugo on travis
deploy:
  provider: script
  script: "cd ./public && git config user.name wolf3d && git add . && git commit -m 'Travis deploy' && git push https://${GTOKEN}@github.com/${GUSER}/${GREPONAME}.git master"
  skip_cleanup: true
  local_dir: public
  keep_history: true
  target_branch: master
  on:
    branch: master
