os: linux
dist: xenial
language: c
script:
  - ./binaries/hugo # This commands builds your website on travis
deploy:
  provider: script
  script: bash -c 'git config user.email "kubilisr-blog-bot@users.noreply.github.com" && git config user.name "kubilisr-blog-bot" && git commit -a -m "Travis build: ${TRAVIS_BUILD_NUMBER}" && git push https://${GBUSER}:${GTOKEN}@github.com/${GUSER}/${GREPONAME} master > /dev/null 2>&1'
  skip_cleanup: true
  local_dir: public
  keep_history: true
  target_branch: master
  on:
    branch: master
