os: linux
dist: xenial
language: c
script:
  - ./binaries/hugo # This command builds blog with hugo on travis
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  local_dir: public
  keep_history: true
  target_branch: master
  on:
    branch: master
